on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  pull-requests: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        if: ${{ github.ref_name == 'main' }}
        uses: googleapis/release-please-action@v4
        # Config file (.release-please-manifest.json) takes precedence

      - name: Checkout
        uses: actions/checkout@v5
        if: ${{ steps.release.outputs.releases_created }}

      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
        if: ${{ steps.release.outputs.releases_created }}

      - name: Install dependencies
        run: npm ci
        if: ${{ steps.release.outputs.releases_created }}

      - name: Run tests
        run: npm run test:cov
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build library
        run: npm run build:lib
        if: ${{ steps.release.outputs.releases_created }}

      - name: Publish to npm
        run: npm publish
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}